### ISSUE TITLE
Exclude a module or code section from strict-mode

### ISSUE THREAD

**Issue by hhsadiq** [fibo/strict-mode#2]
Suppose all of my application logic is wrapped in `strict-mode` like this

```
require('strict-mode')(function () {

// your index.js content

// every *require* call inside this function will have strict mode enabled

})
```

Is there a way we can exclude a module or maybe a section of our custom code from `strict-mode`. I know we can achieve this by writing our desired code outside of `strict-mode` but that does not give elegant solution.

**Comment by fibo** [comment]
Hi,

it is a good point, but, I am sorry: I think it is not possible with current implementation.
As you can see in the code, the function you pass to *strict-mode* is executed here https://github.com/fibo/strict-mode/blob/master/index.js#L36
and I do not see any way to filter modules, for example, by their filename using [module.filename](https://nodejs.org/api/modules.html#modules_module_filename).

On the other hand, I think that the alternative solution you proposed is cheap, anyone can understand it, included the future @fibo and the future @hhsadiq :) something like

```
// your index.js

// This code is not imported as strict cause bla bla bla
export.foo = require('./path/to/no/strict/code.js')

require('strict-mode')(function () {
  export.bar = require('./path/to/strict/code.js')
})
```

However, if you can spot a solution feel free to PR.
